config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  post 'site/search' => 'site#search', as: "search"
  get 'site/map' => 'site#map', as: "map"

  resources :homes
  
end

app/models/home.rb
class Home < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
	validates :address, presence: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: '/images/:style/missing.png'
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def search
    @homes = Home.near params[:search], 20
    render :index
  end

  def new
  	@home = Home.new
  end

	def create
    @home = Home.new (home_params)
    if @home.save
      flash.now[:alert] = 'Issue was successfully created'
      redirect_to @home
    else
      flash.now[:alert] = 'Something went wrong, please fill all the fields and try it again'
      render 'new'
    end
  end

  def index
    if params[:search].present?
      @homes = Home.near(params[:search])
    else
      @homes = Home.all
    end
  end

  def show
    @home = Home.find(params[:id]) 
  end

  def edit
    @home = Home.find(params[:id]) 
  end

  def update
    @home = Home.find(params[:id])
    if @home.update_attributes(home_params)
      redirect_to @home
    else
      flash[:alert] = 'Something went wrong, please try it again'
      render 'edit'
      flash[:alert] = ''
    end
  end

  def destroy
    @home = Home.find(params[:id])
    @home.destroy
    redirect_to homes_path
  end

  private
    def home_params
      params.require(:home).permit(:address, :street_number, :city, :state, :postcode, :country, :name, :surname, :phone_number, :email, :type_pet, :max_pets, :title, :description, :avatar)
    end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
		if params[:search]
			@homes = Home.search(params[:search])
		else
			@homes = Home.all
		end
	end

	def search
    params[:distance] ||= 20
    @homes = Home.near params[:search], params[:distance]
    render :map
  end

  def map
  	@homes = Home.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message
    get_message(:notice) || get_message(:alert)
  end

  private

  def get_message(type)
    if flash[type]
      content_tag :div, class: "message col-md-12 col-xs-12 #{type.to_s}" do
        flash[type]
    	end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/homes/_form.erb
<%= form_for @home do |f| %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :postcode %>
  <%= f.text_field :postcode %>
  <%= f.submit 'Save' %>

<% end %>

app/views/homes/edit.erb
<% if @home.errors.any? %>
    <ul>
      <% @home.errors.full_messages.each do |error| %>
        <li> <%= "#{error}" %> </li>
      <% end %>
    </ul>
<% end %>

<%= form_for  @home do |f| %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :postcode %>
  <%= f.text_field :postcode %>
  <br>
  <%= f.submit 'Save' %>

<% end %>

<br>
<%= link_to("Cancel", @home) %>

app/views/homes/edit.html.erb
<%= render 'partials/form' %>
<br/>
<%= link_to("Cancel", homes_path) %>

app/views/homes/index.html.erb
<% @homes.each do |home| %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading" id="head">
          <div class="panel-title" id="title">
            <span class="hidden-xs"><%= home.title %></span>
          </div>
        </div>
        <div class="panel-body">
          <%= image_tag(asset_path(home.avatar.path(:medium))) if home.avatar? %>
        <div class="col-md-9">
          <ul class="items">
            <li></h2>Name: <%= home.name %></h2></li>
            <li></h2>Surname: <%= home.surname %></h2></li>
            <li></h2>Address: <%= home.address %></h2></li>
            <li></h2>City: <%= home.city %></h2></li>
            <li></h2><b>Number:</b> <%= home.street_number %></h2></li>
            <li></h2>State: <%= home.state %></h2></li>
            <li></h2>Zip code: <%= home.postcode %></h2></li>
            <li></h2>Country: <%= home.country %></h2></li>
            <li></h2>Email: <%= home.email %></h2></li>
            <li></h2>Phone number: <%= home.phone_number %></h2></li>
            <li></h2>Type pet: <%= home.type_pet %></h2></li>
            <li></h2>Max. pets: <%= home.max_pets %></h2></li>
          </ul>
        </div>
        <div class="col-md-12">
          <h2>Description: <%= home.description %></h2>
        </div>
        </div>
        <div class="panel-footer">
          <div class="coupon-code">
            <span class="print">
              <%= link_to("Edit", edit_home_path(home)) %>
            </span>
            <span>
              <%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/homes/new.erb
<% if @home.errors.any? %>
    <ul>
      <% @home.errors.full_messages.each do |error| %>
        <li> <%= "#{error}" %> </li>
      <% end %>
    </ul>
<% end %>

<h1>New Home pa ti</h1>
<%= render "form" %>
<br/>
<%= link_to("Cancel", homes_path) %>

app/views/homes/new.html.erb
<%= render 'partials/form' %>
<br/>
<%= link_to("Cancel", homes_path) %>

app/views/homes/show.erb
<h4>Your home:</h4>

<h5><%= "#{@home.address} - #{@home.postcode}" %></h5>
<br><br>
<%= link_to("Edit", edit_home_path(@home)) %> 
<br><br>
<%= link_to("Back", home_path(@home)) %> 

app/views/homes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading" id="head">
          <div class="panel-title" id="title">
            <span class="hidden-xs"><%= @home.title %></span>
          </div>
        </div>
        <div class="panel-body">
          <%= image_tag(asset_path(@home.avatar.path(:medium))) if @home.avatar? %>
        <div class="col-md-9">
          <ul class="items">
            <li></h2>Name: <%= @home.name %></h2></li>
            <li></h2>Surname: <%= @home.surname %></h2></li>
            <li></h2>Address: <%= @home.address %></h2></li>
            <li></h2>City: <%= @home.city %></h2></li>
            <li></h2><b>Number:</b> <%= @home.street_number %></h2></li>
            <li></h2>State: <%= @home.state %></h2></li>
            <li></h2>Zip code: <%= @home.postcode %></h2></li>
            <li></h2>Country: <%= @home.country %></h2></li>
            <li></h2>Email: <%= @home.email %></h2></li>
            <li></h2>Phone number: <%= @home.phone_number %></h2></li>
            <li></h2>Type pet: <%= @home.type_pet %></h2></li>
            <li></h2>Max. pets: <%= @home.max_pets %></h2></li>
          </ul>
        </div>
        <div class="col-md-12">
          <h2>Description: <%= @home.description %></h2>
        </div>
        </div>
        <div class="panel-footer">
          <div class="coupon-code">
            <span class="print">
              <%= link_to("Edit", edit_home_path(@home)) %>
            </span>
            <span>
              <%= link_to 'Destroy', @home, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PetHome</title>
      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
      <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Luckiest+Guy" %>
      <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Montserrat:700,400" %>
      <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Cabin:400,700" %>
      
      <%= javascript_include_tag 'application' %>
      <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBKXq2Ybcp12gMdRC1qsVsZpRMm_KRbJGw&libraries=places" %>
      <%= yield :javascript_includes %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'partials/navbar' %>
    <%= flash.alert %>
    <%= yield %>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <hr>
      <div class="text-center center-block">
        <p class="txt-railway">- Developed by <b>Rubén Zaldívar</b> -</p>
      </div>
    <hr>
  </div>
</footer>

app/views/partials/_form.html.erb
<% if flash_message != "" %>
  <%= flash_message %>
<% end %>

<!-- Search Field -->
<div class="container">
  <h1 class="title">Register your home</h1>
    <div class="row clearfix">
      <div class="col-md-12 column">
        <form role="form"> 
          <div class="form-group">
          <label>Insert your Address</label>
            <input class="flex-item" id="autocomplete" placeholder="Insert your address" onFocus="geolocate()" type="text"></input>
          </div>
          </form>
            <%= form_for @home, multipart: true, id: "address", class: "form-address" do |f| %>
              <div class="form-group">
                <%= f.label :Address %>
                <%= f.text_field :address, id: "route"  %>
              </div>
              <div class="form-group">
                <%= f.label :Street_Number %>
                <%= f.text_field :street_number, id: "street_number"  %>
              </div>
              <div class="form-group">
                <%= f.label :City %>
                <%= f.text_field :city, id: "locality"  %>
              </div>
              <div class="form-group">
                <%= f.label :State %>
                <%= f.text_field :state, id: "administrative_area_level_1"  %>
              </div>
              <div class="form-group">
                <%= f.label :Zip_Code %>
                <%= f.text_field :postcode, id: "postal_code"  %>
              </div>
              <div class="form-group">
                <%= f.label :Country %>
                <%= f.text_field :country, id: "country"  %>
              </div>
              <div class="form-group">
                <%= f.label :Name %>
                <%= f.text_field :name, id: "name"  %>
              </div>
              <div class="form-group">
                <%= f.label :Surname %>
                <%= f.text_field :surname, id: "surname"  %>
              </div>
              <div class="form-group">
                <%= f.label :Phone_number %>
                <%= f.text_field :phone_number, id: "phone_number"  %>
              </div>
              <div class="form-group">
                <%= f.label :Email %>
                <%= f.text_field :email, id: "email"  %>
              </div>
              <div class="form-group">
                <%= f.label :Type_of_pet %>
                <%= f.select :type_pet, %w(bird cat dog reptile ) %>
              </div>
              <div class="form-group">
                <%= f.label :max_pets %>
                <%= f.number_field :max_pets, in: 1..5, step: 1, id: "max_pets"  %>
              </div>
              <div class="form-group">
                <%= f.label :Title_Advertisement%>
                <%= f.text_field :title, id: "title"  %>
              </div>
              <div class="form-group">
                <%= f.label :Home_description %>
                <%= f.text_area :description, id: "description"  %>
              </div>
              <div class="form-group">
                <%= f.label :Photo %>
                <%= f.file_field :avatar %>
              </div>
              <div class="form-group">
                <%= f.submit 'Save' %>
              </div>
            <% end %>
      </div>
    </div>
</div>

<script>initialize()</script>

app/views/partials/_navbar.html.erb
<!-- NAVBAR MENU -->
<div class="container">
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Pet Home", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home list", homes_path, class: "active" %></li>
          <li><%= link_to "Register home", new_home_path, class: "page-scroll" %></li>
        </ul>
      </div>
    </div>
  </nav>
</div>

      

app/views/site/index.html.erb
<section class="hero is-success is-fullheight">
  <div class="hero-content">
    <div class="container">
      <h1 class="title">
        Feel like at home
      </h1>
      <div id="input-wrapper">
      </div>
	      <p>
		      <%= form_tag(search_path, method: :post, id: "search-form") do %>
		      	<%= text_field_tag :search, nil, value: @query, placeholder: "Search by city and press Enter", class: "form-control" %>
            <%= submit_tag "SEARCH" %>
		      <% end %>
	      </p>
    </div>
  </div>
</section>

<script>initialize()</script>

app/views/site/map.html.erb
<!-- Search bar -->
<div class="container">
	<p>
	  <%= form_tag(search_path, method: :post, id: "search-form") do %>
	  	<%= text_field_tag :search, nil, value: @query, placeholder: "Search by city and press Enter", class: "form-control" %>
	    <%= submit_tag "Search" %>
	  <% end %>
	</p>
</div>
<div id="map"></div>

<!-- Map -->
<script>
  <% if @homes.any? %>
    var coordinates = <%= raw(@homes.map { |home| { lat: home.latitude, lng: home.longitude, add: home.address, post: home.postcode, city: home.city, avatar: home.avatar.path(:medium), state: home.state, str_number: home.street_number, country: home.country, max_pets: home.max_pets, type_pet: home.type_pet, name: home.name, surname: home.surname, email: home.email, phone_num: home.phone_number, title: home.title, desc: home.description, show_url: home_path(home) } }.to_json) %>;
    initMap(coordinates);
  <% else %>
    $("#map").html("There are no homes for your search. Sorry. Try again.")
  <% end %>
</script>